---
title: "Introduction to BIOS524"
# subtitle: "Biostatistical Computing with R"
author: "Mikhail Dozmorov"
institute: "Virginia Commonwealth University"
# date: "`r Sys.Date()`"
date: "08-25-2021"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["xaringan-themer.css", "xaringan-my.css"]
    nature:
      ratio: '16:9'
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
mono_light(
  base_color = "midnightblue",
  header_font_google = google_font("Josefin Sans"),
  text_font_google   = google_font("Montserrat", "500", "500i"),
  code_font_google   = google_font("Droid Mono"),
  link_color = "#8B1A1A", #firebrick4, "deepskyblue1"
  text_font_size = "28px",
  code_font_size = "26px"
)
```

class: center, middle

# Welcome

---
## Logistics

- A two-part course:
    - August 25 - October 13, 2021: R programming
    - October 18 - December 8, 2021: SAS

- **Nitai Mukhopadhyay**, Ph.D., Associate professor, Department of Biostatistics, VCU
    - Bayesian inference, Graphical models, Image analysis, Adaptive Clinical trial designs, Statistical Computing, Markov chain Montecarlo sampling, Multivariate quantile
    
- **Mikhail Dozmorov**, PhD, Associate professor, Department of Biostatistics, VCU
    - Bioinformatics, Genomics, Data Science

.small[ https://medschool.vcu.edu/expertise/detail.html?ID=1180

https://medschool.vcu.edu/expertise/detail.html?id=mdozmorov ]

---
## Biostatistical Computing with R

- Learning through practice - this means you will always do something hands-on

- While doing, you will need to google for help - you will learn a lot from other resources

- Let's maintain a welcoming and supportive environment
    - Ask as many questions during the class as necessary! Worst case - I'll address them later, if not covered during the class
    - Respect each other

---
## Learning Objectives

By the end of this course, you will be able to:

- Understand and utilize R/RStudio

- Share your code on GitHub

- Understand basic data types and data structures in R

- Execute and interpret some basic statistics in R

- Load data files (Excel, Comma Separated Value files) into R/Rstudio, with tips on formatting and data organization

- Filter and format data in R for use with various routines

- Visualize datasets using ggplot2 and understand how to build basic plots using ggplot2 syntax

---
## Rules for interaction

- Join [vcubiostat.slack.com](https://vcubiostat.slack.com/) channel. See [Slack 101](https://slack.com/resources/slack-101)
    - Contact via direct messages, or add others for group conversations
    - Omit formalities, but be respectful and polite
    - I'll try to answer your questions asap, typically, within 24 hours

- E-mail works

---
## Class Assignments

- Homeworks should be submitted via Canvas, or as instructed

- Homeworks are due 1 week after the class. E.g., homework for September 22 class is due September 29, 5:00pm Eastern time

- A final project will conclude the course

- Office hours - by appointment. Message by Slack or e-mail to schedule, or talk with me at class. Zoom meetings are possible.


