---
title: "Tidyverse"
# linktitle: "1. Introduction to RStudio and Images"
date: "2021-09-15"
class_date: "2021-09-15"
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 5
type: docs
weight: 1
pdf:
thumb:
editor_options: 
  chunk_output_type: console
---

## Slides

[Remaster the Tidyverse](https://github.com/rstudio-education/remaster-the-tidyverse) - class materials built by Garrett Grolemund

### Tidyverse, data manipulation

<a href="../../slides/51_Tidyverse_dplyr#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/51_Tidyverse_dplyr.html#1')
```

<a href="../../slides/51_dplyr.R" target="_blank">dplyr.R example code</a>

### Tidyverse, ggplot2

<a href="../../slides/52_Tidyverse_ggplot2#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/52_Tidyverse_ggplot2.html#1')
```

<a href="../../slides/0-companion-script.R" target="_blank">ggplot2 example code</a>. Source: [A Gentle Guide to the Grammar of Graphics with ggplot2](https://github.com/gadenbuie/gentle-ggplot2) by Garrick Aden-Buie

