---
title: "Data management/code best practices"
# linktitle: "1. Introduction to RStudio and Images"
date: "2021-09-22"
class_date: "2021-09-22"
output:
  blogdown::html_page:
    toc: false
menu:
  class:
    parent: Class sessions
    weight: 6
type: docs
weight: 1
pdf:
thumb:
editor_options: 
  chunk_output_type: console
---

## Slides

### Data best practices

<a href="../../slides/61_Data_best_practices#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/61_Data_best_practices.html#1')
```

### Code best practices

<a href="../../slides/62_Code_best_practices#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/62_Code_best_practices.html#1')
```

### Optimization best practices

<a href="../../slides/63_Optimization_best_practices#1" target="_blank">Lecture slides in HTML format</a>

```{r echo=FALSE}
knitr::include_url('../../slides/63_Optimization_best_practices.html#1')
```
